adding image uploader web app
gohil-jay/Macro-Python-Projects pull request #56
Opened 2022-10-09 20:03 UTC by ritishbhardwaj

2022-10-09 20:04 UTC, ritishbhardwaj commented
@gohil-jay 
kindly merge PR

2022-10-10 04:22 UTC, gohil-jay requested changes

2022-10-10 04:22 UTC, gohil-jay commented on imageuploader/myapp/apps.py
> +
It would be great to show the working of the PR in PR's conversation (such as output screenshots).

2022-10-10 04:36 UTC, ritishbhardwaj commented on imageuploader/myapp/apps.py
> +
thanks for considering this PR.
i definitely will make changes and also provide screen shots

2022-10-10 04:49 UTC, ritishbhardwaj commented on imageuploader/myapp/apps.py
> +
## Short description of this project
this web application helps users to save their data (images) in database in a sorted manner. User can easily get out of those old method of finding particular pic on particular date by using this application. it provides solution to user by sorting out the images in such a way that user can easily find out particular image on particular date because of the time stamp over the pic when clicked the pic.

## how to run this web App
- download the code base
- open code in any IDE and open terminal in it
- pip install django
- cd (to this directory) 
- py manage.py runserver
- open any web-browser and fill url http://127.0.0.1:8000/

## screenshots


![WhatsApp Image 2022-10-10 at 10 18 15](https://user-images.githubusercontent.com/81488252/194800655-478e78d6-71d1-4167-bd5f-5d2cc643e84f.jpg)
UI

![WhatsApp Image 2022-10-10 at 10 18 14](https://user-images.githubusercontent.com/81488252/194800680-31866100-e075-4417-8a15-9025011b3e8c.jpg)
creation of tables in database

![WhatsApp Image 2022-10-10 at 10 18 15](https://user-images.githubusercontent.com/81488252/194800704-f236cfd2-095e-4cca-9450-2a5d0b694f28.jpg)
users' uploaded data

2022-10-10 04:51 UTC, ritishbhardwaj commented
@gohil-jay 
I hope you find those comments useful

2022-10-10 04:56 UTC, ritishbhardwaj commented
## Short description of this project

this web application helps users to save their data (images) in database in a sorted manner. User can easily get out of those old method of finding particular pic on particular date by using this application. it provides solution to user by sorting out the images in such a way that user can easily find out particular image on particular date because of the time stamp over the pic when clicked the pic.

## how to run this web App
- download the code base
- open code in any IDE and open terminal in it
- pip install django
- cd (to this directory)
- py manage.py runserver
- open any web-browser and fill url http://127.0.0.1:8000/

## ScreenShots
![194800655-478e78d6-71d1-4167-bd5f-5d2cc643e84f](https://user-images.githubusercontent.com/81488252/194801095-2ebda3e4-9213-420d-9a62-8a36274daf98.jpg)
UI


![194800655-478e78d6-71d1-4167-bd5f-5d2cc643e84f](https://user-images.githubusercontent.com/81488252/194801149-b16bc50d-b392-4f20-95c1-ef8944e50ac8.jpg)
Creation of tables in database

![194800704-f236cfd2-095e-4cca-9450-2a5d0b694f28](https://user-images.githubusercontent.com/81488252/194801205-35aafdb5-9f3f-499e-84b4-9baaed29560e.jpg)
users' uploaded data

2022-10-10 04:57 UTC, ritishbhardwaj commented
@gohil-jay 
i hope you find these changes useful for your repo
any other change you want????

2022-10-10 08:22 UTC, gohil-jay approved these changes

2022-10-10 08:23 UTC, gohil-jay commented
This is good to go.

2022-10-10 08:23 UTC, merged